### ISSUE TITLE
https - Self Signed Certs

### ISSUE THREAD

**Issue by KevinSheedy** [namshi/shisha#27]
When I try to test a connection over https that uses a self-signed cert, I get the following error:

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: self signed certificate in certificate chain
        at Error (native)
        at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
        at TLSSocket.emit (events.js:104:17)
        at TLSSocket._finishInit (_tls_wrap.js:460:8)

Would it be possible to add support for unsigned ssl certs?

I have done this previously be using [https.request()](https://nodejs.org/api/https.html#https_https_request_options_callback) with the following two flags set:

    requestCert: true
    rejectUnauthorized: false
    
Reference:
https://nodejs.org/api/https.html#https_https_request_options_callback
https://nodejs.org/api/tls.html

**Comment by mohdhallal** [comment]
Hello Kevin,

I have opened a PR about this, let wait for the guys to review it.

Basically, I added an option to pass the CA through shisha and use it when creating the request.

`rejectUnauthorized: false` can be misleading as issues like an expired certificate will not be detected and shisha will report what people might consider false results.

Thanks for reporting and cheers!
